# ==============================================
# mxm/foundry/config/environment.yaml
# ----------------------------------------------
# ==============================================

dev: {}

prod: {}
