# ==============================================
# mxm/foundry/config/machine.yaml
# ----------------------------------------------
# ==============================================

bridge: {}

wildling: {}

monolith: {}
