# ==============================================
# mxm/foundry/config/profile.yaml
# ----------------------------------------------
# ==============================================

default: {}

research: {}

ci: {}
